### ISSUE TITLE
Sync calculations

### ISSUE THREAD

**Issue by sbooth** [jnpdx/AudioEngineLoopbackLatencyTest#1]
Apologies for abusing the issues- I didn't have your email address.

I believe I've improved the timing sync for the built-in audio on my MBP with the following code:

https://github.com/sbooth/AudioEngineLoopbackLatencyTest/blob/main/AudioEngineLoopbackLatencyTest/AudioManager.swift

I need to experiment with more devices. It doesn't work with my display audio, although I wonder if that is because it doesn't report accurate latencies.

**Comment by jnpdx** [comment]
I'm impressed with the persistence you have in coming back to this! Unfortunately, this code pushes everything _way_ out of sync on my MBP (default hardware).  Eyeballing the graph, it looks like about 1200 samples off to me.

Using a similar template to yours in the code, here are the numbers my machine reports:
```
// Output: 
// kAudioDevicePropertySafetyOffset:    93
// kAudioDevicePropertyLatency:          399
// kAudioStreamPropertyLatency:         0
// kAudioDevicePropertyBufferFrameSize: 512

// Input:
// kAudioDevicePropertySafetyOffset:     66
// kAudioDevicePropertyLatency:            0
// kAudioStreamPropertyLatency:         0
// kAudioDevicePropertyBufferFrameSize:  512
```

I think it's reasonably to have skepticism about the stream latency properties my machine reports.  However, I have no insight as to why that number is being reported as 0.  It could be:
1) The machine is reporting that number via another property (like folded into the kAudioDevicePropertyLatency)
2) It's reporting a totally bogus number, which could either be:
  a) How the system behaves in a stock setup
  b) Something that I unknowingly have affected at some point.  I find this slightly unlikely since I don't have any special sound drivers/kernel extensions/etc like BlackHole or SoundFlower or anything like that.  But, I could be wrong.

If you ever do need my email John (at) johnnastos.com works

**Comment by sbooth** [comment]
That's too bad. I have one last device I will test today using a physical cable for loopback which should be interesting. 

Apparently I'm not up for solving this problem in the general case!
